SMS/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMS.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using SMS.Repositories;

namespace SMS.Controllers
{
    public class ClassController : Controller
    {
        StudentRepo studrepo = new StudentRepo();
        ClassRepo classRepo = new ClassRepo();
        SectionRepo sectionRepo = new SectionRepo();
        FeeStructureRepo feestructrepo = new FeeStructureRepo();


        List<Class> classlist = new List<Class>();

        List<Section> sectionlist = new List<Section>();

        public ClassController()
        {

            ViewBag.MaxClassId = classRepo.GetNextId();

        }


        public ActionResult ClassList()
        {
            List<Class> clist = new List<Class>();

            clist = classRepo.GetAll();

            return View(clist);
        }


        [HttpGet]
        public ActionResult AddClass(int id = 0)
        {
            Class cl = new Class();


            if (id > 0)
            {
                cl = classRepo.GetById(id);

            }


            return View(cl);
        }

        [HttpPost]
        public ActionResult AddClass(Class cl)
        {
            

            if (ModelState.IsValid)
            {


                try
                {
                    if (cl.ClassId > 0)
                    {

                        string result1 = classRepo.Update(cl);
                        if (result1 == "Success")
                        {
                            ModelState.Clear();
                            TempData["Success"] = "Updated successfully...";
                        }
                        else
                        {
                            TempData["Error"] = "Failed to update...";
                        }

                        string result2 = feestructrepo.UpdateById(cl);
                        if (result2 == "Success")
                        {
                            ModelState.Clear();
                            TempData["Success"] = "Updated successfully...";
                        }
                        else
                        {
                            TempData["Error"] = "Failed to update...";
                        }

                    }
                    else
                    {
                        string checkClassNameExists = classRepo.CheckClassName(cl.ClassName);

                        if (checkClassNameExists == "Error")
                        {
                            TempData["Error"] = "This class name already exists";
                        }
                        else
                        {

                            string result1 = classRepo.Create(cl);
                            if (result1 == "Success")
                            {
                                ModelState.Clear();
                                TempData["Success"] = "Created successfully...";
                            }
                            else
                            {
                                TempData["Error"] = "Failed to create...";
                            }


                            string result2 = feestructrepo.CreateById(cl);
                            if (result2 == "Success")
                            {
                                ModelState.Clear();
                                TempData["Success"] = "Created successfully...";
                            }
                            else
                            {
                                TempData["Error"] = "Failed to create...";
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    TempData["Error"] = "Failed to update/create...";
                    throw ex.InnerException;
                }
            }
            else
            {
                TempData["Error"] = "Fill out all the details!";
            }

            return View(cl);
        }

// use this later - if u need it 


        [HttpGet]
        public JsonResult GetSectionsByClassId(int classId)
        {
            List<Section> sList = sectionRepo.GetSectionsByClassId(classId);
            return Json(sList, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult GetClassFeeById(int classId)
        {

            decimal classFee = feestructrepo.GetClassFeeById(classId);
            return Json(classFee, JsonRequestBehavior.AllowGet);
        }



        public ActionResult DeleteClass(int id)
        {
            try
            {
                string result = classRepo.Delete(id);
                if (result == "Success")
                    TempData["Success"] = "Record Deleted successfully...";
                else
                    TempData["Error"] = "Unable to delete...";

                // return RedirectToAction("SubCategoryList");
            }
            catch (Exception ex)
            {
                throw ex.InnerException;
            }

            //modify below 
            return RedirectToAction("GetList");
        }


    }
}

SMS/Controllers/FeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMS.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using SMS.Repositories;


namespace SMS.Controllers
{
    public class FeeController : Controller
    {
        // GET: Fee

        FeeStructureRepo feestructrepo = new FeeStructureRepo();
        ClassRepo classRepo = new ClassRepo();

        List<Class> classlist = new List<Class>();
        List<FeeStructure> feestruct = new List<FeeStructure>();

        public FeeController()
        {
            classlist = classRepo.GetAll();
            ViewBag.ClassList = classlist;


            ViewBag.MaxFeeStructId = feestructrepo.GetNextId();

        }

        [HttpGet]
        public ActionResult FeeStructList()
        {
            List<FeeStructure> feeList = new List<FeeStructure>();

            feeList = feestructrepo.GetAll();

            return View(feeList);
        }

        [HttpPost]

        public ActionResult FeeStructList(int drpClass = 0)
        {
            if (Session["UserType"].ToString() != "Admin")
            {
                return RedirectToAction("Authentication", "Login");
            }
            else
            {
                Session["Searched"] = true;

                List<FeeStructure> feeList = new List<FeeStructure>();

                feeList = feestructrepo.GetAll();


                if (drpClass > 0)
                {
                    feeList = feeList.Where(c => c.ClassId == drpClass).ToList();
                }

                return View(feeList);
            }
        }

    

    [HttpGet]
        public ActionResult AddFeeStruct(int id = 0)
        {
            FeeStructure feestruct = new FeeStructure();


            if (id > 0)
            {
                feestruct = feestructrepo.GetById(id);

            }


            return View(feestruct);
        }

        [HttpPost]
        public ActionResult AddFeeStruct(FeeStructure feeStruct)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (feeStruct.FeeId > 0)
                    {
                        string result = feestructrepo.Update(feeStruct);
                        if (result == "Success")
                        {
                            ModelState.Clear();
                            TempData["Success"] = "Updated successfully...";
                        }
                        else
                        {
                            TempData["Error"] = "Failed to update...";
                        }
                    }
                    else
                    {
                        string result = feestructrepo.Create(feeStruct);
                        if (result == "Success")
                        {
                            ModelState.Clear();
                            TempData["Success"] = "Created successfully...";
                        }
                        else
                        {
                            TempData["Error"] = "Failed to create...";
                        }
                    }
                }
                catch (Exception ex)
                {
                    TempData["Error"] = "Failed to update/create...";
                    throw ex.InnerException;
                }
            }
            else
            {
                TempData["Error"] = "Fill out all the details!";
            }

            return View(feeStruct);
        }

        /**

                [HttpGet]
                public JsonResult GetSectionsByClassId(int classId)
                {
                    List<Section> sList = sectionRepo.GetSectionsByClassId(classId);
                    return Json(sList, JsonRequestBehavior.AllowGet);
                }


                [HttpGet]
                public JsonResult GetClassFeeById(int classId)
                {

                    decimal classFee = feestructrepo.GetClassFeeById(classId);
                    return Json(classFee, JsonRequestBehavior.AllowGet);
                }

        **/

        public ActionResult DeleteFeeStruct(int id)
        {
            try
            {
                string result = feestructrepo.Delete(id);
                if (result == "Success")
                    TempData["Success"] = "Record Deleted successfully...";
                else
                    TempData["Error"] = "Unable to delete...";

                // return RedirectToAction("SubCategoryList");
            }
            catch (Exception ex)
            {
                throw ex.InnerException;
            }

            //modify below 
            return RedirectToAction("GetList");
        }

    }
}

SMS/Controllers/SectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMS.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using SMS.Repositories;

namespace SMS.Controllers
{
    public class SectionController : Controller
    {
        // GET: Section

        SectionRepo sectionrepo = new SectionRepo();
        ClassRepo classRepo = new ClassRepo();


        List<Class> classlist = new List<Class>();

        public SectionController()
        {
            classlist = classRepo.GetAll();
            ViewBag.ClassList = classlist;

            ViewBag.MaxSectionId = sectionrepo.GetNextId();

        }


        public ActionResult SectionList()
        {
            List<Section> sList = new List<Section>();

            sList = sectionrepo.GetAll();

            return View(sList);
        }


        [HttpGet]
        public ActionResult AddSection(int id = 0)
        {
            Section section = new Section();

            if (id > 0)
            {
                section = sectionrepo.GetById(id);

            }

            return View(section);
        }

        [HttpPost]
        public ActionResult AddSection(Section section)
        {

            if (ModelState.IsValid)
            {

                try
                {
                    string checkSectionNameExists = sectionrepo.CheckSectionName(section);

                    if (checkSectionNameExists == "Error")
                    {
                        TempData["Error"] = "This section name already exists";
                    }
                    else
                    {
                        if (section.SectionId > 0)
                        {
                        string result = sectionrepo.Update(section);
                        if (result == "Success")
                        {
                            ModelState.Clear();
                            TempData["Success"] = "Updated successfully...";
                        }
                        else
                        {
                            TempData["Error"] = "Failed to update...";
                        }
                    }
                        else
                        {
                            string result = sectionrepo.Create(section);
                            if (result == "Success")
                            {
                                ModelState.Clear();
                                TempData["Success"] = "Created successfully...";
                            }

                            else
                            {
                                TempData["Error"] = "Failed to create...";
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    TempData["Error"] = "Failed to update/create...";
                    throw ex.InnerException;
                }
            }
            else
            {
                TempData["Error"] = "Fill out all the details!";
            }

            return View(section);
        }


/**
        [HttpGet]
        public JsonResult GetSectionsByClassId(int classId)
        {
            List<Section> sList = sectionRepo.GetSectionsByClassId(classId);
            return Json(sList, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult GetClassFeeById(int classId)
        {

            decimal classFee = feestructrepo.GetClassFeeById(classId);
            return Json(classFee, JsonRequestBehavior.AllowGet);
        }

**/

        public ActionResult DeleteSection(int id)
        {
            try
            {
                string result = sectionrepo.Delete(id);
                if (result == "Success")
                    TempData["Success"] = "Record Deleted successfully...";
                else
                    TempData["Error"] = "Unable to delete...";

                // return RedirectToAction("SubCategoryList");
            }
            catch (Exception ex)
            {
                throw ex.InnerException;
            }

            //modify below 
            return RedirectToAction("GetList");
        }
    }
}

SMS/Views/Login/AdminAuthentication.cshtml

@{
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Authentication</title>
</head>
<body>
    <div>
        <h2>Login</h2>

        @if (TempData["Success"] != null)
        {
            <div class="alert alert-success">@TempData["Success"]</div>
        }

        @if (TempData["Error"] != null)
        {
            <div class="alert alert-danger">@TempData["Error"]</div>
        }

        @using (Html.BeginForm("AdminAuthentication", "Login", FormMethod.Post))
        {
            <table class="table">
                <tr>
                    <td>
                        @Html.Label("username", "User Name")
                    </td>
                    <td>
                        @Html.TextBox("username", null, new { @class = "form-control", type = "text", @pattern = "[A-Za-z  ]*" })
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.Label("password", "Password")
                    </td>
                    <td>
                        @Html.TextBox("password", null, new { @class = "form-control", type = "number" })
                    </td>
                </tr>
                <tr>
                    <td>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </td>
                </tr>

            </table>
        }
        <br />
        <br />
        <br />

      

    </div>
</body>
</html>

SMS/Views/Login/EmpAuthentication.cshtml

@{
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Authentication</title>
</head>
<body>
    <div>
        <h2>Login</h2>

        @if (TempData["Success"] != null)
        {
            <div class="alert alert-success">@TempData["Success"]</div>
        }

        @if (TempData["Error"] != null)
        {
            <div class="alert alert-danger">@TempData["Error"]</div>
        }

        @using (Html.BeginForm("EmpAuthentication", "Login", FormMethod.Post))
        {
            <table class="table">
                <tr>
                    <td>
                        @Html.Label("username", "User Name")
                    </td>
                    <td>
                        @Html.TextBox("username", null, new { @class = "form-control", type = "text", @pattern = "[A-Za-z  ]*" })
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.Label("password", "Password")
                    </td>
                    <td>
                        @Html.TextBox("password", null, new { @class = "form-control", type = "number" })
                    </td>
                </tr>
                <tr>
                    <td>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </td>
                </tr>

            </table>
        }
        <br />
        <br />
        <br />

        @Html.ActionLink("Register", "EmpRegister", "Registration", null, new { @class = "btn btn-primary" })

    </div>
</body>
</html>

SMS/Views/Login/GetUserType.cshtml

@{
    Layout = "~/Views/Shared/Layout2.cshtml";
    List<SMS.UserType> a = new List<SMS.UserType>();
    a.Add(new SMS.UserType() {Id = "Employer", Q = "Employer" });
    a.Add(new SMS.UserType() { Id = "Student", Q = "Student" });
    a.Add(new SMS.UserType() { Id = "Admin", Q = "Admin" });
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetUserType</title>
</head>
<body>
    <div>
        @if (TempData["Success"] != null)
        {
            <div class="alert alert-success">@TempData["Success"]</div>
        }

        @if (TempData["Error"] != null)
        {
            <div class="alert alert-danger">@TempData["Error"]</div>
        }

        @using (Html.BeginForm("GetUserType", "Login", FormMethod.Post))
        {

            <table class="table">

                <tr>
                    <td>
                        @Html.Label("Login as:")
                    </td>
                    <td>
                        @Html.DropDownList(
                 "type", new SelectList(a, "Id", "Q"), new { @class = "form-control" })

                    </td>
                </tr>



                <tr>
                    <td>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </td>
                </tr>

                </table>

                }

        </div>
</body>
</html>

SMS/Views/Login/MainPage.cshtml
@model SMS.Models.Admin

@{
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MainPage</title>
</head>
<body>
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success">@TempData["Success"]</div>
    }

    @if (TempData["Error"] != null)
    {
        <div class="alert alert-danger">@TempData["Error"]</div>
    }

    <div>
        <div class="container">
            <h2>Welcome, @Html.DisplayFor(model => model.AdminName)!!!</h2>
            <p>Admin ID is: @Html.DisplayFor(model => model.AdminId)</p>
        </div>
    </div>


    <div class="navbar">
        <ul>
            <li><a href="@Url.Action("EmpList", "EmpCRUD")"> Edit/View All Employee Records</a></li>
            <li><a href="@Url.Action("StudList", "StudCRUD")"> Edit/View All Student Records</a></li>
            <li><a href="@Url.Action("DeptList", "Department")"> Edit/View All Department Records</a></li>
            <li><a href="@Url.Action("ClassList", "Class")"> Edit/View All Class Records</a></li>
            <li><a href="@Url.Action("SectionList", "Section")">Edit/View all Section Records</a></li>
            <li><a href="@Url.Action("FeeList", "Fee")">Edit/View all Fee Records</a></li>
            <li><a href="@Url.Action("FeeCollectionList", "FeeCollection")">Edit/View all Fee Collection Records</a></li>
            <li><a href="@Url.Action("StudRegister", "Registration")"> Register a New Student</a></li>
            <li><a href="@Url.Action("EmpRegister", "Registration")"> Register a New Employer </a></li>
            <li><a href="@Url.Action("AdminRegister", "Registration")"> Register a New Admin </a></li>

        </ul>

        @Html.ActionLink("Logout", "Logout", "Login", null, new { @class = "btn btn-danger" })
    </div>


</body>
</html>

SMS/Views/Login/StudAuthentication.cshtml

@{
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Authentication</title>
</head>
<body>
    <div>
        <h2>Login</h2>

        @if (TempData["Success"] != null)
        {
            <div class="alert alert-success">@TempData["Success"]</div>
        }

        @if (TempData["Error"] != null)
        {
            <div class="alert alert-danger">@TempData["Error"]</div>
        }

        @using (Html.BeginForm("StudAuthentication", "Login", FormMethod.Post))
        {
            <table class="table">
                <tr>
                    <td>
                        @Html.Label("username", "User Name")
                    </td>
                    <td>
                        @Html.TextBox("username", null, new
                   {
                       @class = "form-control",
                       type = "text",
                       @pattern = "[A-Za-z  ]*"
                   })

                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.Label("password", "Password")
                    </td>
                    <td>
                        @Html.TextBox("password", null, new { @class = "form-control" , type = "number" })
                    </td>
                </tr>
                <tr>
                    <td>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </td>
                </tr>

            </table>
        }
        <br />
        <br />
        <br />

        @Html.ActionLink("Register", "StudRegister", "Registration", null, new { @class = "btn btn-primary" })

    </div>
</body>
</html>