SMS/Models/FeeCollection.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SMS.Models
{
    public class FeeCollection
    {

    
        public int? FeeColId { get; set; }

        
        public int StudentId { get; set; }

        
        public int ClassId { get; set; }

       
        public bool Installment1 { get; set; }

        
        public bool Installment2 { get; set; }

     
        public bool Installment3 { get; set; }

       
        public string FeeStatus { get; set; }
        public string StudentName { get; set; }

        public string ClassName { get; set; }


    }
}

SMS/Controllers/FeeCollectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SMS.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Diagnostics;
using SMS.Repositories;

namespace SMS.Controllers
{
   
    public class FeeCollectionController : Controller
    {
        // GET: FeeCollection

        FeeCollectionRepo feecolrepo = new FeeCollectionRepo();
        FeeStructureRepo feestructrepo = new FeeStructureRepo();

        ClassRepo classRepo = new ClassRepo();
        StudentRepo studRepo = new StudentRepo();

        List<Class> classlist = new List<Class>();

        List<Student> studlist = new List<Student>();



        public FeeCollectionController()
        {

            classlist = classRepo.GetAll();
            ViewBag.ClassList = classlist;



            studlist = studRepo.GetAll();
            ViewBag.StudentList = studlist;

            ViewBag.MaxFeeColId = feecolrepo.GetNextId();

        }

        [HttpGet]
        public ActionResult FeeColList(int? classId)
        {
            List<FeeCollection> fList = new List<FeeCollection>();

            if (classId.HasValue)
            {
                // Filter the FeeCollection records based on the selected ClassId
                fList = feecolrepo.GetAll().Where(f => f.ClassId == classId.Value).ToList();
            }
            else
            {
                // If no ClassId is selected, return all records
                fList = feecolrepo.GetAll();
            }

            // Pass the filtered list to the view
            return View(fList);
        }


        [HttpGet]
        public ActionResult AddFeeCol(int id = 0)
        {
            FeeCollection feecol = new FeeCollection();


            if (id > 0)
            {
                feecol = feecolrepo.GetById(id);

            }


            return View(feecol);
        }

        [HttpPost]
        public ActionResult AddFeeCol(FeeCollection feecol)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Debug.WriteLine(feecol.FeeColId);
                    if (feecol.FeeColId > 0)
                    {
                        string result = feecolrepo.Update(feecol);
                        if (result == "Success")
                        {
                            ModelState.Clear();
                            TempData["Success"] = "Updated successfully...";
                        }
                        else
                        {
                            TempData["Error"] = "Failed to update...";
                        }
                    }
                    else
                    {
                        string result = feecolrepo.Create(feecol);
                        if (result == "Success")
                        {
                            ModelState.Clear();
                            TempData["Success"] = "Created successfully...";
                        }
                        else
                        {
                            TempData["Error"] = "Failed to create...";
                        }
                    }
                }
                catch (Exception ex)
                {
                    Debug.WriteLine(ex.Message);
                   
                    TempData["Error"] = "Failed to update/create...";
                    throw ex.InnerException;
                   
                }
            }
            else
            {
                TempData["Error"] = "Fill out all the details!";
            }

            return View(feecol);
        }




        public JsonResult GetInstallations(int classId)
        {
   
            List<decimal> installations = new List<decimal>();

            var installation1 = feestructrepo.GetInstallation1ByClassId(classId); 
            var installation2 = feestructrepo.GetInstallation2ByClassId(classId); 
            var installation3 = feestructrepo.GetInstallation3ByClassId(classId); 

            installations.Add(installation1);
            installations.Add(installation2);
            installations.Add(installation3);

            // Return the list of installation values as JSON
            return Json(installations,JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetInstallationsByStudId(int studid)
        {

            List<bool> installations = new List<bool>();

            bool installation1 = feecolrepo.GetInstallation1ByStudId(studid) == true; 
            bool installation2 = feecolrepo.GetInstallation2ByStudId(studid) == true; 
            bool installation3 = feecolrepo.GetInstallation3ByStudId(studid) == true; 


            installations.Add(installation1);
            installations.Add(installation2);
            installations.Add(installation3);

            // Return the list of installation values as JSON
            return Json(installations,JsonRequestBehavior.AllowGet);
        }


        public ActionResult DeleteFeeCol(int id)
        {
            try
            {
                string result = feecolrepo.Delete(id);
                if (result == "Success")
                    TempData["Success"] = "Record Deleted successfully...";
                else
                    TempData["Error"] = "Unable to delete...";

                // return RedirectToAction("SubCategoryList");
            }
            catch (Exception ex)
            {
                throw ex.InnerException;
            }

            //modify below 
            return RedirectToAction("GetList");
        }

    }
}

SMS/Controllers/StudCRUDController.cs
using SMS.Models;
using SMS.Repositories;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web.Mvc;
using OfficeOpenXml;

using System.IO;

namespace SMS.Controllers
{
    public class StudCRUDController : Controller
    {

        StudentRepo studrepo = new StudentRepo();
        ClassRepo classRepo = new ClassRepo();
        SectionRepo sectionRepo = new SectionRepo();
        FeeStructureRepo feestructrepo = new FeeStructureRepo();


        List<Class> classlist = new List<Class>();

        List<Student> sList = new List<Student>();

        List<Section> sectionlist = new List<Section>();

        public StudCRUDController()
        {
            classlist = classRepo.GetAll();
            ViewBag.ClassList = classlist;

            sectionlist = sectionRepo.GetAll();
            ViewBag.SectionList = sectionlist;

            sList = studrepo.GetAll();
            ViewBag.StudentList = sList;

            ViewBag.MaxStudId = studrepo.GetNextId();

        }


        public ActionResult StudList()
        {


            sList = studrepo.GetAll();

            return View(sList);
        }


        [HttpGet]
        public ActionResult AddStud(int id = 0)
        {
            Student stud = new Student();


            if (id > 0)
            {
                stud = studrepo.GetById(id);

            }


            return View(stud);
        }

        [HttpPost]
        public ActionResult AddStud(Student stud)
        {


            if (ModelState.IsValid)
            {

                try
                {
                    if (stud.StudentId > 0)
                    {
                        string result = studrepo.Update(stud);
                        if (result == "Success")
                        {
                            ModelState.Clear();
                            TempData["Success"] = "Updated successfully...";
                        }
                        else
                        {
                            TempData["Error"] = "Failed to update...";
                        }
                    }
                    else
                    {
                        string result = studrepo.Create(stud);
                        if (result == "Success")
                        {
                            ModelState.Clear();
                            TempData["Success"] = "Created successfully...";
                        }
                        else
                        {
                            TempData["Error"] = "Failed to create...";
                        }
                    }
                }
                catch (Exception ex)
                {
                    TempData["Error"] = "Failed to update/create...";
                    throw ex.InnerException;
                }
            }
            else
            {
                TempData["Error"] = "Fill out all the details!";
            }

            return View(stud);
        }



        [HttpGet]
        public JsonResult GetSectionsByClassId(int classId)
        {
            List<Section> sList = sectionRepo.GetSectionsByClassId(classId);
            return Json(sList, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public JsonResult GetStudentsByClassId(int classId)
        {
            List<Student> sList = studrepo.GetStudentsByClassId(classId);
            return Json(sList, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public JsonResult GetClassFeeById(int classId)
        {

            decimal classFee = feestructrepo.GetClassFeeById(classId);
            return Json(classFee, JsonRequestBehavior.AllowGet);
        }



        public ActionResult DeleteStud(int id)
        {
            try
            {
                string result = studrepo.Delete(id);
                if (result == "Success")
                    TempData["Success"] = "Record Deleted successfully...";
                else
                    TempData["Error"] = "Unable to delete...";

                // return RedirectToAction("SubCategoryList");
            }
            catch (Exception ex)
            {
                throw ex.InnerException;
            }

            //modify below 
            return RedirectToAction("GetList");
        }


        [HttpGet]
        public ActionResult UploadStudent()
        {
            return View();
        }

        [HttpPost]

        public ActionResult UploadStudent(System.Web.HttpPostedFileBase fileUpload)
        {
            if (fileUpload == null || fileUpload.ContentLength == 0)
            {
                TempData["Error"] = "Please upload a valid Excel file.";
                return RedirectToAction("UploadStudent");
            }

            using (var stream = new MemoryStream())
            {
                fileUpload.InputStream.CopyTo(stream);

                ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

                using (var excel = new ExcelPackage(stream))
                {
                    var workSheet = excel.Workbook.Worksheets.FirstOrDefault();

                    if (workSheet == null)
                    {
                        TempData["Error"] = "The uploaded file does not contain any worksheet.";
                        return RedirectToAction("UploadStudent");
                    }

                    var start = workSheet.Dimension.Start;
                    var end = workSheet.Dimension.End;

                    List<string> validationErrors = new List<string>();


                    int studentId = 0; 
                    DateTime dob; 
                    int classId = 0;
                    int sectionId = 0;
                    int contactNo = 0;
                    int studentPassword = 0;
                    int studentFee = 0;


                 
                    for (var r = start.Row + 1; r <= end.Row; r++)
                    {
                        string errorMessage = "";

                        // Validate StudentId - no ext - update alt
                        string studentIdStr = workSheet.Cells[r, 1].Value?.ToString();
                        if (string.IsNullOrEmpty(studentIdStr))
                        {
                            errorMessage += $"Row {r}: StudentId cannot be null or empty. ";
                        }
                        else if (!int.TryParse(studentIdStr, out  studentId))
                        {
                            errorMessage += $"Row {r}: Invalid StudentId type. ";
                        }

                        // Validate StudentName - no ext
                        string studentName = workSheet.Cells[r, 2].Value?.ToString();
                        if (string.IsNullOrEmpty(studentName))
                        {
                            errorMessage += $"Row {r}: StudentName cannot be empty. ";
                        }
                        else if (!studentName.All(char.IsLetter)) 
                        {
                            errorMessage += $"Row {r}: StudentName must contain only letters. ";
                        }

                        // Validate DOB - no ext
                        if (!DateTime.TryParse(workSheet.Cells[r, 3].Value?.ToString(), out  dob))
                        {
                            errorMessage += $"Row {r}: Invalid Date of Birth. ";
                        }

                        // Validate ClassId - ext needed (in else)
                        string classIdStr = workSheet.Cells[r, 4].Value?.ToString();
                        if (string.IsNullOrEmpty(classIdStr))
                        {
                            errorMessage += $"Row {r}: ClassId cannot be null or empty. ";
                        }
                        else if (!int.TryParse(classIdStr, out  classId))
                        {
                            errorMessage += $"Row {r}: Invalid ClassId. ";
                        }
                        else
                        {
                            //check if the class id exists 
                            string result = classRepo.CheckClassId(classId);

                            if (result == "Error")
                            {
                                errorMessage += $"Row {r}: ClassId {classId} does not exist. ";
                            }

                        }

                        // Validate SectionId - ext needed (in else)
                        string sectionIdStr = workSheet.Cells[r, 5].Value?.ToString();
                        if (string.IsNullOrEmpty(sectionIdStr))
                        {
                            errorMessage += $"Row {r}: SectionId cannot be null or empty. ";
                        }
                        else if (!int.TryParse(sectionIdStr, out  sectionId))
                        {
                            errorMessage += $"Row {r}: Invalid SectionId. ";
                        }
                        else
                        {
                            string result = sectionRepo.CheckSectionId(sectionId);

                            if (result == "Error")
                            {
                                errorMessage += $"Row {r}: SectionId {sectionId} does not exist. ";
                            }

                        }

                        // Validate FatherName - no ext
                        string fatherName = workSheet.Cells[r, 6].Value?.ToString();
                        if (string.IsNullOrEmpty(fatherName))
                        {

SMS/Views/FeeCollection/AddFeeCol.cshtml
@model SMS.Models.FeeCollection

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Fees</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" />

    <style>
        body {
            background-color: #4B0082;
        }

        h2 {
            color: #4c0070;
        }

        .container {
            margin-top: 50px;
            max-width: 600px;
        }

        .card {
            border: none;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        }

        .btn-primary {
            background-color: #4c0070;
            border-color: #4c0070;
        }

            .btn-primary:hover {
                background-color: #320050;
            }

        .form-label {
            color: #4c0070;
        }

        .form-control, .form-select {
            background-color: #E6E6FA;
        }

            .form-control:focus {
                border-color: #4c0070;
                box-shadow: 0 0 0 0.2rem rgba(76, 0, 112, 0.25);
            }

        .alert {
            margin-top: 20px;
        }

        .required:after {
            content: "*";
            color: red;
            margin-left: 5px;
        }
    </style>
</head>
<body>

    <div class="container">
        <div class="card">
            <div class="card-body">
                <h2 class="text-center">Add Fees</h2>

                @if (TempData["Success"] != null)
                {
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        @TempData["Success"]
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                }

                @if (TempData["Error"] != null)
                {
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        @TempData["Error"]
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                }


                @using (Html.BeginForm("AddFeeCol", "FeeCollection", FormMethod.Post))
                {
                    @Html.HiddenFor(model => model.FeeColId)

                    @Html.HiddenFor(m => m.FeeStatus)
                    @Html.HiddenFor(m => m.ClassName)
                    @Html.HiddenFor(m => m.StudentName)


                    <div class="mb-3">
                        @Html.LabelFor(m => m.StudentId, "Student", new { @class = "form-label required" })
                        @Html.DropDownListFor(model => model.StudentId, new SelectList(ViewBag.StudentList, "StudentId", "StudentName"),
                            "-- Select --", new { @class = "form-select", @id = "StudentId" })
                        @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
                    </div>

                    <div class="mb-3">
                        @Html.LabelFor(m => m.ClassId, "Class", new { @class = "form-label required" })
                        @Html.DropDownListFor(model => model.ClassId, new SelectList(ViewBag.ClassList, "ClassId", "ClassName"),
                            "-- Select --", new { @class = "form-select", @id = "classDropdown" })
                        @Html.ValidationMessageFor(model => model.ClassId, "", new { @class = "text-danger" })
                    </div>

                    <div class="mb-3">
                        @Html.LabelFor(m => m.Installment1, "Installment 1", new { @class = "form-label", @id = "Installment1" })
                        @Html.CheckBoxFor(m => m.Installment1, new { @id = "IsChecked1" })
                    </div>

                    <div class="mb-3">
                        @Html.LabelFor(m => m.Installment2, "Installment 2", new { @class = "form-label", @id = "Installment2" })
                        @Html.CheckBoxFor(m => m.Installment2, new { @id = "IsChecked2" })
                    </div>

                    <div class="mb-3">
                        @Html.LabelFor(m => m.Installment3, "Installment 3", new { @class = "form-label", @id = "Installment3" })
                        @Html.CheckBoxFor(m => m.Installment3, new { @id = "IsChecked3" })
                    </div>




                    <button type="submit" class="btn btn-primary w-100">Save Fees</button>
                }
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.bundle.min.js"></script>

    <script>

$(document).ready(function () {

    // Handle ClassId dropdown change
    $('#classDropdown').change(function () {
      
        $('#StudentId').attr('disabled', false);
        var classId = $(this).val();


        if (classId) {
         
            $.ajax({
                url: '@Url.Action("GetStudentsByClassId", "StudCRUD")',
                type: 'GET',
                data: { classId: classId },
                success: function (data) {
                    $('#StudentId').empty().append('<option value="">-- Select Section --</option>');
                    $.each(data, function (index, item) {
                        $('#StudentId').append('<option value="' + item.StudentId + '">' + item.StudentName + '</option>');
                    });
                },
                error: function () {
                    alert('Error loading students.');
                }
            });

          
            $.ajax({
                url: '@Url.Action("GetInstallations", "FeeCollection")',  
                type: 'GET',
                data: { classId: classId },
                success: function (response) {
                   
                    $('#Installation1').val(response[0]);
                    $('#Installation2').val(response[1]);
                    $('#Installation3').val(response[2]);
                },
                error: function () {
                    alert('Error fetching installations.');
                }
            });
        } else {
            
            $('#Installation1, #Installation2, #Installation3').val('');
            $('#StudentId').attr('disabled', true);
        }
    });

    // Handle StudentId dropdown change
    $('#StudentId').change(function () {
    
        var classId = $('#classDropdown').val();

        // Only proceed if a class has been selected
        if (classId) {
            var studentId = $(this).val();

        
            if (studentId) {
                $.ajax({
                    url: '@Url.Action("GetInstallationsByStudId", "FeeCollection")',  
                    type: 'GET',
                    data: { studId: studentId },
                    success: function (response) {

                        alert("got in inst by stud id");
                        // Assuming response contains the checkbox status (true/false)
                        $('#IsChecked1').prop('checked', response[0]); 
                        $('#IsChecked2').prop('checked', response[1]); 
                        $('#IsChecked3').prop('checked', response[2]);

                        // Disable checkboxes if true
                        if (response[0]) {
                            $('#IsChecked1').prop('disabled', true);  
                        }
                        if (response[1]) {
                            $('#IsChecked2').prop('disabled', true);  
                        }
                        if (response[2]) {
                            $('#IsChecked3').prop('disabled', true); 
                        }
                    },
                    error: function () {
                        alert('Error fetching checkbox status.');
                    }
                });
            } else {
                // Uncheck and enable checkboxes if no student is selected
                $('#IsChecked1').prop('checked', false).prop('disabled', false);
                $('#IsChecked2').prop('checked', false).prop('disabled', false);
                $('#IsChecked3').prop('checked', false).prop('disabled', false);
            }
        }
    });

  
    $('#IsChecked1').on('change', function () {
        if ($(this).prop('checked')) {
            $('input[name="Installment1"]').val('true');
        } else {
            $('input[name="Installment1"]').val('false');
        }
    });

    $('#IsChecked2').on('change', function () {
        if ($(this).prop('checked')) {
            $('input[name="Installment2"]').val('true');
        } else {
            $('input[name="Installment2"]').val('false');
        }
    });

    $('#IsChecked3').on('change', function () {
        if ($(this).prop('checked')) {
            $('input[name="Installment3"]').val('true');
        } else {
            $('input[name="Installment3"]').val('false');
        }
    });

  
    if ($('#IsChecked1').prop('checked')) {
        $('input[name="Installment1"]').val('true');
        $('#IsChecked1').prop('disabled', true);  
    } else {
        $('input[name="Installment1"]').val('false');
    }

    if ($('#IsChecked2').prop('checked')) {
        $('input[name="Installment2"]').val('true');
        $('#IsChecked2').prop('disabled', true);  
    } else {
        $('input[name="Installment2"]').val('false');
    }

    if ($('#IsChecked3').prop('checked')) {
        $('input[name="Installment3"]').val('true');
        $('#IsChecked3').prop('disabled', true);  
    } else {
        $('input[name="Installment3"]').val('false');
    }


    if ($('#IsChecked1').prop('disabled')) {
        $('input[name="Installment1"]').val('true');  
    } else {
        $('input[name="Installment1"]').val('false'); 
    }

    if ($('#IsChecked2').prop('disabled')) {
        $('input[name="Installment2"]').val('true');  
    } else {
        $('input[name="Installment2"]').val('false'); 
    }

    if ($('#IsChecked3').prop('disabled')) {
        $('input[name="Installment3"]').val('true');  
    } else {
        $('input[name="Installment3"]').val('false');
    }

});



    </script>



</body>
</html>

SMS/Views/FeeCollection/FeeColList.cshtml
@model IEnumerable<SMS.Models.FeeCollection>

@{
    Layout = "~/Views/Shared/Layout2.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Fee List</title>
</head>
<body>
    <div>
        @if (TempData["Success"] != null)
        {
            <div class="alert alert-success">@TempData["Success"]</div>}

        @if (TempData["Error"] != null)
        {
            <div class="alert alert-danger"> @TempData["Error"]</div>}

        <h2>Fee List</h2>
        <div>@Html.ActionLink("New", "AddFeeCol", "FeeCollection")</div>

        @using (Html.BeginForm("FeeColList", "FeeCollection", FormMethod.Get))
        {

            <table>
                <tr>
                    <td>
                        @Html.Label("Select Class Name")
                    </td>
                    <td>
                        @Html.DropDownList("ClassId", new SelectList(ViewBag.ClassList, "ClassId", "ClassName", Model.FirstOrDefault()?.ClassId), "-- Select --", new { @class = "form-select", @id = "classDropdown" })
                    </td>
                </tr>


            </table>

            <button type="submit" class="btn btn-primary">Search</button>}

        <table class="table">
            <thead>
                <tr>
                    <th>Fee Collection Id</th>
                    <th>Student Name</th>
                    <th>Class Name</th>
                    <th> Installment1</th>
                    <th> Installment2</th>
                    <th> Installment3</th>
                    <th>Fee Status</th>
                    <th>Student Name</th>

                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var f in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(model => f.FeeColId)</td>


                        <td>@Html.DisplayFor(model => f.StudentId)</td>
                        <td>@Html.DisplayFor(model => f.ClassName)</td>

                        @if (f.Installment1 == true)
                        {
                            <td>Paid</td>
                        }
                        else
                        {
                            <td>Unpaid</td>
                        }

                        @if (f.Installment2 == true)
                        {
                            <td>Paid</td>
                        }
                        else
                        {
                            <td>Unpaid</td>
                        }

                        @if (f.Installment3 == true)
                        {
                            <td>Paid</td>
                        }
                        else
                        {
                            <td>Unpaid</td>
                        }


                        <td>@Html.DisplayFor(model => f.FeeStatus) </td>
                        <td>@Html.DisplayFor(model => f.StudentName) </td>


                        <td>
                            <a href="@Url.Action("AddFeeCol", "FeeCollection", new { id = f.FeeColId })">Edit</a>
                            <a href="@Url.Action("DeleteFeeCol", "FeeCollection", new { id = f.FeeColId })">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>


        @Html.ActionLink("Go Back to Main Page", "MainPage", "Login", null, new { @class = "btn btn-success" })


    </div>



</body>
</html>